	{{-- 	<script src="/adminmtr/vendors/jquery.repeater/src/lib.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/jquery.repeater/src/jquery.input.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/jquery.repeater/src/repeater.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/jquery-form/dist/jquery.form.min.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/block-ui/jquery.blockUI.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/js/framework/components/plugins/forms/bootstrap-datepicker.init.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/bootstrap-datetime-picker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/bootstrap-timepicker/js/bootstrap-timepicker.min.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/js/framework/components/plugins/forms/bootstrap-timepicker.init.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/js/framework/components/plugins/forms/bootstrap-daterangepicker.init.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/bootstrap-maxlength/src/bootstrap-maxlength.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/bootstrap-switch/dist/js/bootstrap-switch.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/js/framework/components/plugins/forms/bootstrap-switch.init.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/vendors/bootstrap-multiselectsplitter/bootstrap-multiselectsplitter.min.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/bootstrap-select/dist/js/bootstrap-select.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/select2/dist/js/select2.full.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/typeahead.js/dist/typeahead.bundle.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/handlebars/dist/handlebars.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/inputmask/dist/jquery.inputmask.bundle.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/inputmask/dist/inputmask/inputmask.date.extensions.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/inputmask/dist/inputmask/inputmask.numeric.extensions.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/inputmask/dist/inputmask/inputmask.phone.extensions.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/nouislider/distribute/nouislider.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/owl.carousel/dist/owl.carousel.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/autosize/dist/autosize.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/clipboard/dist/clipboard.min.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/ion-rangeslider/js/ion.rangeSlider.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/dropzone/dist/dropzone.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/summernote/dist/summernote.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/markdown/lib/markdown.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/bootstrap-markdown/js/bootstrap-markdown.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/js/framework/components/plugins/forms/bootstrap-markdown.init.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/jquery-validation/dist/jquery.validate.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/jquery-validation/dist/additional-methods.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/js/framework/components/plugins/forms/jquery-validation.init.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/bootstrap-notify/bootstrap-notify.min.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/js/framework/components/plugins/base/bootstrap-notify.init.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/toastr/build/toastr.min.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/jstree/dist/jstree.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/raphael/raphael.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/morris.js/morris.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/chartist/dist/chartist.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/chart.js/dist/Chart.bundle.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/js/framework/components/plugins/charts/chart.init.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/vendors/bootstrap-session-timeout/dist/bootstrap-session-timeout.min.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/vendors/jquery-idletimer/idle-timer.min.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/waypoints/lib/jquery.waypoints.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/counterup/jquery.counterup.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/es6-promise-polyfill/promise.min.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/sweetalert2/dist/sweetalert2.min.js" type="text/javascript"></script>
		<script src="/adminmtr/vendors/js/framework/components/plugins/base/sweetalert2.init.js" type="text/javascript"></script> --}}
